# Generated by Django 5.1.7 on 2025-03-14 06:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_registro_horario_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrohorario',
            unique_together={('usuario', 'fecha')},
        ),
    ]
